get http://localhost:3000 

###
curl http://localhost:3000/movies

###
curl http://localhost:3000/movies/65b03afed45be0bf43ed864e


###
curl -X POST http://localhost:3000/movies \
-H "Content-Type: application/json" \
-d '{
    "movieTitle": "Harry Potter",
    "movieDirector": "Mike Johnson",
    "leadActor": "Daniel Radcliff",
    "supportingActor": "Emma Watson",
    "synopsis": "Boy finds out hes a wizard",
    "beginning": "Living with the Dursleys",
    "ending": "Defeats the dark Lord"
}'

###

curl -X PUT http://localhost:3000/movies/65b03afed45be0bf43ed864e \
-H "Content-Type: application/json" \
-d '{
    "movieTitle": "HI Title",
    "movieDirector": "New Director",
    "leadActor": "New Lead Actor",
    "supportingActor": "New Supporting Actor",
    "synopsis": "Updated Synopsis",
    "beginning": "Updated Beginning",
    "ending": "Updated Ending"
}'

###

curl -X DELETE http://localhost:3000/movies/65b17d6540d9808e01fc228b
